import "./globals.css";
import { Inter, Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"], variable: "--bodyFont" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
const thunder = localFont({
  src: "../../public/font/Thunder-BlackLC.ttf",
  variable: "--headingFont",
});

const custom = localFont({
  src: "../../public/font/custom.ttf",
  variable: "--heading",
});
const monum = localFont({
  src: "../../public/font/MonumentExtended-Ultrabold.otf",
  variable: "--custom",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${thunder.variable} ${montserrat.className} ${custom.variable} ${monum.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
