import "./globals.css";
import { Inter, Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"], variable: "--bodyFont" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";
const thunder = localFont({
  src: "../../public/font/Thunder-BlackLC.ttf",
  variable: "--headingFont",
});

const custom = localFont({
  src: "../../public/font/custom.ttf",
  variable: "--heading",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${thunder.variable} ${montserrat.className} ${custom.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
